### ISSUE TITLE
Cant use the "Break Blocks" event

### ISSUE THREAD

**Issue by Saelman** [Blackvein/Quests#453]
so when i try to use the break blocks event (1) i instead am sent to the Place Blocks event (3)  and when i try Place Blocks (3) im sent to Place blocks (correct place) im unable to use the break block event due to it sending me to the Place blocks event. any ideas on what i can do to try and fix this.

**Comment by FlyingPikachu** [comment]
What is your Quests version?

**Comment by NoblessHamster** [comment]
Uh.. Actually, I have a same issue
(Version : Quests 2.7.4 (dev build))

**Comment by NoblessHamster** [comment]
When I attempt to create "Break blocks" stage, editor sent me message only "Break blocks" information.

**Comment by Saelman** [comment]
same version. 2.7.4

i dont get that msg i just get sent to the place block stage. its as 1 and 3 go to the same place

**Comment by PantallazoAzul** [comment]
Same bug... version: 2.7.4-b118

**Comment by pacificminer** [comment]
Fix this ffs

**Comment by FlyingPikachu** [comment]
Fixed in 52c6d388acfee5c733c651153ae67b48236bd771

Use http://ci.ac3-servers.eu/job/Quests/120/ once available

**Comment by Reversiya** [comment]
Latest version has multiple issues - downloading, loading. On paperspigot 1.8.8 it will not load at all. Other versions still have this bug, would recommend re-updating.
